from django.contrib.admin import site;from .models import Estado,Sede,Tipo,Muestra,CodificacionInterpretacion,Organo,Naturaleza,Formato,Imagen, Aumento
site.register(Estado)
site.register(Sede)
site.register(Tipo)
site.register(Muestra)
site.register(CodificacionInterpretacion)
site.register(Organo)
site.register(Naturaleza)
site.register(Formato)
site.register(Aumento)
site.register(Imagen)
