version: '3.8'

services:
  db: 
    image: mysql:latest
    restart: always
    container_name: mysql-anatomia
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/mysqldata:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=anatomia
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - anatomia-network

  backend:
    build: ./backend
    container_name: django-anatomia
    command: ["sh", "-c", "python wait_for_mysql.py && python manage.py makemigrations api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=anatomia
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=db
    networks:
      - anatomia-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue-anatomia
    ports:
      - "8080:8080"
    networks:
      - anatomia-network
volumes:
  db-data:
networks:
  anatomia-network: